version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: study-and-sync
    ports:
      - "5432:5432"
    volumes:
      - ./database/data:/var/lib/postgresql/data
    restart: unless-stopped
